name: Model CI
on: [push]

jobs:
  build-model:
    name: Build, test, and upload model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-ci-requirements.txt

    - name: Run unit tests 
      run: |
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: en - Train model
      run: |
        cd bot
        rasa train --config languages/en/config.yml --domain languages/en/domain.yml --data languages/en/data languages/stories.md --augmentation 0 --out languages/en/models/

    - name: en - Run Through Test stories
      run: |
        cd bot
        rasa test --stories languages/en/tests/conversation_tests.md --fail-on-prediction-errors
    
    - name: en - Cross-validate NLU model
      run: |
        cd bot
        rasa test nlu --nlu languages/en/data/

    - name: br - Train model
      run: |
        cd bot
        rasa train --config languages/br/config.yml --domain languages/br/domain.yml --data languages/br/data languages/stories.md --out languages/br/models/  

    - name: br - Run Through Test stories
      run: |
        cd bot
        rasa test --model languages/br/ --stories languages/en/tests/conversation_tests.md --fail-on-prediction-errors
    
    - name: br - Cross-validate NLU model
      run: |
        cd bot
        rasa test nlu --nlu languages/en/data/
