name: ci-tests
on: [pull_request]

jobs:

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-ci-requirements.txt

    - name: Run unit tests 
      run: |
        cd bot
        pytest --doctest-modules --cov=bot --cov-report=html

    - name: Save tests
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests
        path: bot/htmlcov

  training-testing:
    name: Train and test bot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-ci-requirements.txt

    - name: en - Train model
      run: |
        cd bot
        rasa train --config languages/en/config.yml --domain languages/en/domain.yml --data languages/en/data languages/stories.md --augmentation 0 --out languages/en/models/

    - name: en - Run Through Test stories
      run: |
        cd bot
        rasa test --model languages/en/models --nlu languages/en/data --stories languages/en/tests/conversation_tests.md --out languages/en/results
    
    - name: en - Save tests
      uses: actions/upload-artifact@v2
      with:
        name: en-tests
        path: bot/languages/en/results

    - name: br - Train model
      run: |
        cd bot
        rasa train --config languages/br/config.yml --domain languages/br/domain.yml --data languages/br/data languages/stories.md --augmentation 0 --out languages/br/models/  

    - name: br - Run Through Test stories
      run: |
        cd bot
        rasa test --model languages/br/models --nlu languages/br/data --stories languages/br/tests/conversation_tests.md --out languages/br/results

    - name: br - Save tests
      uses: actions/upload-artifact@v2
      with:
        name: br-tests
        path: bot/languages/br/results
